### ISSUE TITLE
New rule: no-interfaces

### ISSUE THREAD

**Issue by MaxDac** [eslint-functional/eslint-plugin-functional#572]
## Suggestion

The new rule would forbid defining interfaces in favour of types. The reason behind this rule would be to avoid the existence of two language features that offer almost the same functionality. The rule would suggest the usage of `type`s instead.

I created an implementation example in [this fork](https://github.com/MaxDac/eslint-plugin-functional) if that can be useful.

**Comment by RebeccaStevens** [comment]
We used to have this rule but we deprecated it back in [v3.2.2](https://github.com/eslint-functional/eslint-plugin-functional/blob/main/CHANGELOG.md#v322---2021-07-23) and removed it in [v4.0.0](https://github.com/eslint-functional/eslint-plugin-functional/blob/main/CHANGELOG.md#400-2021-10-17).

We did this simply because there now exists [@typescript-eslint/consistent-type-definitions](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-definitions.md) which does this behavior.

**Comment by MaxDac** [comment]
Apologies, I didn't notice it when I searched for a similar rule, that's exactly what I needed, thanks for the explanation!
