### ISSUE TITLE
prefer-immutable-types: Async function must return Promise type

### ISSUE THREAD

**Issue by dacevedo12** [eslint-functional/eslint-plugin-functional#777]
## Bug Report

https://typescript.tv/errors/#ts1064

There's no way to type the return as Readonly<Promise<>>

**Comment by jonaskello** [comment]
The rule that the return value from an `async` function must be a `Promise<T>` is enforced by the typescript compiler. I don't think we can do anything about this case using linting rules. I would suggest that you open an issue on the typescript repo about this case.

You can however return `Readonly<Promise<T>>` if you don't mark the function as `async`.

**Comment by jonaskello** [comment]
Just a thought, perhaps you meant to return `Promise<Readonly<T>>` ?

**Comment by dacevedo12** [comment]
`Promise<Readonly<T>>` doesn't satisfy prefer-immutable-types

`Return type should have an immutability of at least "Immutable" (actual: "ReadonlyShallow"). eslintfunctional/prefer-immutable-types`

Same error goes for `Readonly<Promise<T>>` without marking the function as `async`

**Comment by RebeccaStevens** [comment]
@dacevedo12

`Promise<Readonly<T>>` is what should be used for async functions to make the return type a shallowly readonly type.

You seem to have the rule set up to enforce `Immutable` return types which are more strict.
You may want to use [`ReadonlyDeep`](https://github.com/sindresorhus/type-fest#:~:text=accept%20undefined.-,ReadonlyDeep,-%2D%20Create%20a%20deeply) instead of `Readonly` to get deeply readonly types.
However, getting fully immutable types from a mutable type isn't really possible in all circumstances. You usually need to manually write the types to ensure they are immutable.

I'd recommend you reduce the enforcement level of type immutablity you're using for the rule.
